/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuccursalesRouteImport } from './routes/succursales'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as QuiSommesNousRouteImport } from './routes/qui-sommes-nous'
import { Route as PartenairesRouteImport } from './routes/partenaires'
import { Route as ExpertiseRouteImport } from './routes/expertise'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ActualitesRouteImport } from './routes/actualites'
import { Route as IndexRouteImport } from './routes/index'

const SuccursalesRoute = SuccursalesRouteImport.update({
  id: '/succursales',
  path: '/succursales',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const QuiSommesNousRoute = QuiSommesNousRouteImport.update({
  id: '/qui-sommes-nous',
  path: '/qui-sommes-nous',
  getParentRoute: () => rootRouteImport,
} as any)
const PartenairesRoute = PartenairesRouteImport.update({
  id: '/partenaires',
  path: '/partenaires',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertiseRoute = ExpertiseRouteImport.update({
  id: '/expertise',
  path: '/expertise',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesRoute = ActualitesRouteImport.update({
  id: '/actualites',
  path: '/actualites',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actualites': typeof ActualitesRoute
  '/contact': typeof ContactRoute
  '/expertise': typeof ExpertiseRoute
  '/partenaires': typeof PartenairesRoute
  '/qui-sommes-nous': typeof QuiSommesNousRoute
  '/services': typeof ServicesRoute
  '/succursales': typeof SuccursalesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actualites': typeof ActualitesRoute
  '/contact': typeof ContactRoute
  '/expertise': typeof ExpertiseRoute
  '/partenaires': typeof PartenairesRoute
  '/qui-sommes-nous': typeof QuiSommesNousRoute
  '/services': typeof ServicesRoute
  '/succursales': typeof SuccursalesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actualites': typeof ActualitesRoute
  '/contact': typeof ContactRoute
  '/expertise': typeof ExpertiseRoute
  '/partenaires': typeof PartenairesRoute
  '/qui-sommes-nous': typeof QuiSommesNousRoute
  '/services': typeof ServicesRoute
  '/succursales': typeof SuccursalesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actualites'
    | '/contact'
    | '/expertise'
    | '/partenaires'
    | '/qui-sommes-nous'
    | '/services'
    | '/succursales'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actualites'
    | '/contact'
    | '/expertise'
    | '/partenaires'
    | '/qui-sommes-nous'
    | '/services'
    | '/succursales'
  id:
    | '__root__'
    | '/'
    | '/actualites'
    | '/contact'
    | '/expertise'
    | '/partenaires'
    | '/qui-sommes-nous'
    | '/services'
    | '/succursales'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActualitesRoute: typeof ActualitesRoute
  ContactRoute: typeof ContactRoute
  ExpertiseRoute: typeof ExpertiseRoute
  PartenairesRoute: typeof PartenairesRoute
  QuiSommesNousRoute: typeof QuiSommesNousRoute
  ServicesRoute: typeof ServicesRoute
  SuccursalesRoute: typeof SuccursalesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/succursales': {
      id: '/succursales'
      path: '/succursales'
      fullPath: '/succursales'
      preLoaderRoute: typeof SuccursalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qui-sommes-nous': {
      id: '/qui-sommes-nous'
      path: '/qui-sommes-nous'
      fullPath: '/qui-sommes-nous'
      preLoaderRoute: typeof QuiSommesNousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partenaires': {
      id: '/partenaires'
      path: '/partenaires'
      fullPath: '/partenaires'
      preLoaderRoute: typeof PartenairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expertise': {
      id: '/expertise'
      path: '/expertise'
      fullPath: '/expertise'
      preLoaderRoute: typeof ExpertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites': {
      id: '/actualites'
      path: '/actualites'
      fullPath: '/actualites'
      preLoaderRoute: typeof ActualitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActualitesRoute: ActualitesRoute,
  ContactRoute: ContactRoute,
  ExpertiseRoute: ExpertiseRoute,
  PartenairesRoute: PartenairesRoute,
  QuiSommesNousRoute: QuiSommesNousRoute,
  ServicesRoute: ServicesRoute,
  SuccursalesRoute: SuccursalesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
